### ISSUE TITLE
Running OF under Windows, WSL2, Python 3.97

### ISSUE THREAD

**Issue by gitwjr** [cta-wave/device-observation-framework#34] opened 2021-10-26 19:02 UTC
When I run the command
"python3 observation_framework,py --<file>" with the file name for the recording which is stored in "device-observation-framework" I get the following:

brose@Bill-Lenovo-Laptop:/mnt/d/device-observation-framework$ python3 observation_framework.py --A101920211GOPR
Traceback (most recent call last):
  File "observation_framework.py", line 29, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

also tried "python3 observation_framework --d:/device-observation-framework/<filename> with and without the file name. 
All return the exact same error: No module named 'cv2'

Also, how does the zbar QR code get called? It is stored in the same drive as the device-observation-framework so its path is known. Does it need to be started before running the OF?

**Comment by yanj-github** [comment] 2021-11-01 07:54
> 
> 
> Found the "official" way to disable WSL2. After restart I confirmed it was not running. However, Docker Desktop fails to run without it running. Re-enabled WSL2 and Docker runs fine but still getting the no cv2 error.

Sorry for delay in response. 
Can you try to install opencv again manually please? 
`pip install --no-cache-dir opencv-python==4.5.2.52`
This requires python version 3.6 or greater and pip version 3 to be installed and on the execution PATH.
Can you check with "pip -V"?
Please make sure you use correct pip for your selected python. Sometimes it appears to be pip3 instead of pip.

**Comment by cta-source** [comment] 2021-11-01 13:12
Does this install need to be done at a regular command terminal window, or inside the relevant Docker container?

**Comment by gitwjr** [comment] 2021-11-01 13:55
@yanj-github Tried your advice. Result: 
PS C:\Users\brose> pip install --no-cache-dir opencv-python==4.5.2.52
Requirement already satisfied: opencv-python==4.5.2.52 in c:\users\brose\appdata\local\programs\python\python39\lib\site-packages (4.5.2.52)
Requirement already satisfied: numpy>=1.19.3 in c:\users\brose\appdata\local\programs\python\python39\lib\site-packages (from opencv-python==4.5.2.52) (1.21.3)
PS C:\Users\brose>

**Comment by yanj-github** [comment] 2021-11-01 14:04
> 
> 
> Does this install need to be done at a regular command terminal window, or inside the relevant Docker container?

We have tested on windows without container. So I would recomand to use command on regular windows terminal. 
Might work on docker or similar containter but havent been tested fully.

**Comment by yanj-github** [comment] 2021-11-01 14:19
> 
> 
> @yanj-github Tried your advice. Ran using Powershell terminal as admin. Result: PS C:\Users\brose> pip install --no-cache-dir opencv-python==4.5.2.52 Requirement already satisfied: opencv-python==4.5.2.52 in c:\users\brose\appdata\local\programs\python\python39\lib\site-packages (4.5.2.52) Requirement already satisfied: numpy>=1.19.3 in c:\users\brose\appdata\local\programs\python\python39\lib\site-packages (from opencv-python==4.5.2.52) (1.21.3) PS C:\Users\brose>

Unfotunatly I cannot replicate your fault here I will try to do more test. I guess there might be due to multiple pythong version or pip version installed. while waiting can you check if the site-packages path is on the system envoriment settings?  If not might need to add it manually.

**Comment by gitwjr** [comment] 2021-11-01 16:24
@yanj-github When I run "whereis pip" I get 
pip: /mnt/c/Users/brose/AppData/Local/Programs/Python/Python39/Scripts/pip.exe /mnt/c/Users/brose/AppData/Local/Programs/Python/Python39/Scripts/pip3.exe /mnt/c/Users/brose/AppData/Local/Programs/Python/Python39/Lib/site-packages/pip

When I look at the Scripts, I see three pip applications listed: pip; pip3; and pip39 
Not clear to me if that means I have 3 versions installed or if the latest one installs the the others for backwards compatibility. I have the path to pip3 in my paths but not to pip or pip39.

**Comment by yanj-github** [comment] 2021-11-01 17:03
> 
> 
> @yanj-github When I run "whereis pip" I get pip: /mnt/c/Users/brose/AppData/Local/Programs/Python/Python39/Scripts/pip.exe /mnt/c/Users/brose/AppData/Local/Programs/Python/Python39/Scripts/pip3.exe /mnt/c/Users/brose/AppData/Local/Programs/Python/Python39/Lib/site-packages/pip
> 
> When I look at the Scripts, I see three pip applications listed: pip; pip3; and pip39 Not clear to me if that means I have 3 versions installed or if the latest one installs the the others for backwards compatibility. I have the path to pip3 in my paths but not to pip or pip39. Still getting no cv2 although I have the path to cv2 in paths as well and it appears the module is there when I open the cv2 folder.

What do you see when you do "python -V" and "python3 -V" you can try to run OF with python3 is "python -V" is lower. 
It looks like the problem is due to multiple version of pip. Not sure which one is used by which python?
We only tested any tried on regular windows, it seem you have WSL2. I am not sure how things will map in this case. 
Either "python" or "python3" whichever you use to run OF need to map to pip then pip map to correct opencv module. 

We recommand to use it on regular windows if this is possible to you please?

**Comment by gitwjr** [comment] 2021-11-01 17:59
@yanj-github Results:
PS C:\Users\brose> python --version
Python 3.9.7
PS C:\Users\brose> pip --version
pip 21.3.1 from C:\Users\brose\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)
PS C:\Users\brose> python3 --version
python3: The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by gitwjr** [comment] 2021-11-01 18:16
If I run  "python3 observation_framework.py --input 10212021GoProFile
1" I get the cv2 error. If I run it using "python observation..." or "python39 observation..." I get "python (or python39) command not found".

**Comment by gitwjr** [comment] 2021-11-01 19:08
@yanj-github py-h results in python versions 3.9.64 and 3.10.64 installed. I do not have the path to 3.10.64 in my paths. 
pip list and pip3 list result in the same package/version sets:
PS C:\Users\brose> pip list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.7
configparser       5.0.2
idna               3.3
isodate            0.6.0
numpy              1.21.3
opencv-python      4.5.2.52
pip                21.3.1
pyzbar             0.1.8
requests           2.26.0
setuptools         57.4.0
six                1.16.0
urllib3            1.26.7

PS C:\Users\brose> pip3 list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.7
configparser       5.0.2
idna               3.3
isodate            0.6.0
numpy              1.21.3
opencv-python      4.5.2.52
pip                21.3.1
pyzbar             0.1.8
requests           2.26.0
setuptools         57.4.0
six                1.16.0
urllib3            1.26.7

**Comment by yanj-github** [comment] 2021-11-02 10:49
@gitwjr It seems that you have mutiple python and pip. Clean reinstallation might be easier than figure out a link problem. I would "pip uninstall" of the modules OF uses and uninstall all his Windows pythons. Then do clean installation of python and run install_win.bat from a Windows CMD. Can you try that please?

**Comment by gitwjr** [comment] 2021-11-02 19:58
I uninstalled all pip packages, and all pip and python installations. I reinstalled pip and python and ran install_win.bat. The packages reinstalled. Then ran the observation_framework.py --install xxx (file name - its in the device-installation-framework folder): Same result no module cv2. Tried with the full path as well. No change. The file is mp4. 
Is there a sample file I can try to make certain its not something having to do with my camera capture?
Also, I have the path to cv2 entered. Its in the Python39/Lib/site-packages folder. Is that the cv2 module the error refers to?

**Comment by yanj-github** [comment] 2021-11-10 09:24
I think the OF should work now @gitwjr will you close this issue when it resolved please?

**Comment by gitwjr** [comment] 2021-11-10 16:28
It was determined that the OF needs to run on Windows outside of WSL2. With Yan's help we ran it outside of WSL2 and it ran. However, the results showed it failed to detect QR Test ID code (even though it matched the one the runner was looking for) due to the fact that the runner I used when I captured the prior video file was an older version that is not compatible with the OF version I am using. I reloaded the most current Runner and imported new content using PowerShell to run the build and import .bat commands (rather than the .sh versions I previously used). A brief test of 2 content files showed resulted in both passing while running on the Host machine (no OF). I now have to set up the camera and run the tests again to create a new video file to see if the OF works as expected.

**Comment by gitwjr** [comment] 2021-11-10 20:21
I ran a new test and recorded it. I then ran the OF using the same PowerShell session we used on Tuesday. The OF ran and checked the frames. The results failed. The test ID (Token) from the results page of the test run matches the log file below: 

INFO     QR code area for full scan is set to [317, 317, 780, 800] for mezzanine QR code, and [1244, 361, 1672, 797] for test status QR code.
INFO     Analysing 'd:\device-observation-framework\10212021GoProFile2.mp4'...
Processed to frame 0...
INFO     Entering log file: logs/46b2cd3e-425c-11ec-ad9b-0242ac110002/session.log
INFO     Start a New test: avc_15_30_60-2021-09-09-local/fullscreen-playback-of-switching-sets__ss1.html
ERROR    Serious error is detected, when analysing ['d:\\device-observation-framework\\10212021GoProFile2.mp4']!Failed to get a parameter:'playout' for the test 'avc_15_30_60-2021-09-09-local/fullscreen-playback-of-switching-sets__ss1.html'
INFO     Device Observation Framework has finished analysing all selected recordings, Device Observation Framework is exiting.

**Comment by yanj-github** [comment] 2021-11-11 08:43
Hi @gitwjr  Thanks for updating. I just checked and I cannot see avc_15_30_60-2021-09-09-local/fullscreen-playback-of-switching-sets__ss1.html is configured on test runner test-config.json file.

**Comment by yanj-github** [comment] 2021-11-11 12:23
Hi @gitwjr I have raise issue on decptf test to get the playout updated.
While you are waiting you can try tests which are not required playout parameter.
I suggest you to try simple 8.2 Sequential Track Playback test.

**Comment by yanj-github** [comment] 2021-11-15 15:26
@gitwjr the issue should be fixed please try update your TR.

**Comment by gitwjr** [comment] 2021-11-16 20:21
I reloaded the Test Runner by deleting the prior docker container and image and the prior build. I then opened a terminal in the target folder and ran ./build.bat master. That used to say "latest" I believe. Then ran compose up -d. The resulting container is named dpctf-deploy-master with "other" shown under it. The image is /dpctf, TAG latest and shows in use. 

When I run http://localhost:8000/_wave/index.html I get 
This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
 
I also entered my IP address shown using ipconfig "10.0.0.106" in place of "localhost". Same result.

**Comment by gitwjr** [comment] 2021-11-16 20:59
@yanj-github Continuing from last comment. When we were online together last we looked for my computer's IP address using ipconfig, you identified it, I believe, as "172.22.128.1". This is actually the IP for my Ethernet adapter. I remember we added this somewhere but can't remember where. My computer (link-local) is 10.0.0.106 and my web server is 127.0.0.1. However, if I enter any of the following "http://localhost" in any browser (or replace <localhost> with <172.22.128.1> or <127.0.0.1> or <10.0.0.106> I get the connection refused error.  i.e. all local IP addresses return connection refused. Yet if I run "ping <any of above local addresses>" I get a response. No problems with any external web sites.  Very frustrating and confusing. I do see my etc/hosts file appears to be fine as far as I can tell.

**Comment by jpiesing** [comment] 2021-11-16 21:04
I know almost nothing about Windows but ...
The web server will be listening for incoming connections on one or more IP addresses.
I would have expected the web server to be listening on localhost (127.0.0.1) or the IP address of the ethernet adaptor or both. You need it to be listening on the latter for a phone, tablet or PC to be able to connect to it. Only a browser on the same computer as is running the web server will be able to connect to 127.0.01.
If you can find out which IP address(es) the web server is listening on then that is what you need to connect to.

**Comment by jpiesing** [comment] 2021-11-16 22:02
@gitwjr That needs someone who knows far more about docker and windows than I do :(

**Comment by gitwjr** [comment] 2021-11-17 00:49
Also refuses to connect to http://Bill-Lenovo-Laptop which is the computer name. But I can ping it. So all localhost access is refused on all browsers running on this computer while all of the do reply to pings and all show as listening on multiple ports each. I can find nothing online that points to a solution.

**Comment by yanj-github** [comment] 2021-11-17 09:23
@gitwjr To start to looking I suggest if you do "docker ps" to see whether TR is running or not. It will show dpctf is running and listning to port.

**Comment by jpiesing** [comment] 2021-11-17 11:38
> @gitwjr To start to looking I suggest if you do "docker ps" to see whether TR is running or not. It will show dpctf is running and listning to port.

If that suggests it should all be working then it might be worth double checking that the windows firewall hasn't got turned back on again.

**Comment by gitwjr** [comment] 2021-11-17 16:01
@jpiesing @yanj-github I have tried disabling private, public and domain firewalls but no change. When I run docker ps I get
PS C:\Users\brose> docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED        STATUS                          PORTS     NAMES
93fe35a9a0d6   dpctf:latest   "/bin/sh -c 'ln -s .…"   38 hours ago   Restarting (1) 19 seconds ago             dpctf

I ran the Windows troubleshooter for accessing "localhost" and it returned "The remote device or resource won't accept the connections on port HTTP. The computer of device you are tryin to reach is available but it doesn't support what you are trying to do. This might be a configuration issue or a limitation of the device."

Under the Windows IP Configuration report it notes that IP Routing and WINS Proxy are both disabled. But from what I read these should not be needed for localhost. 

I checked the routing table (attached to the troubleshooter report):
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0         10.0.0.1       10.0.0.106     25
         10.0.0.0    255.255.255.0         On-link        10.0.0.106    281
       10.0.0.106  255.255.255.255         On-link        10.0.0.106    281
       10.0.0.255  255.255.255.255         On-link        10.0.0.106    281
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
     172.22.128.0    255.255.240.0         On-link      172.22.128.1   5256
     172.22.128.1  255.255.255.255         On-link      172.22.128.1   5256
   172.22.143.255  255.255.255.255         On-link      172.22.128.1   5256
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link        10.0.0.106    281
        224.0.0.0        240.0.0.0         On-link      172.22.128.1   5256
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link        10.0.0.106    281
  255.255.255.255  255.255.255.255         On-link      172.22.128.1   5256

**Comment by yanj-github** [comment] 2021-11-17 16:05
38 hours ago Restarting (1) 19 seconds ago dpctf 
It seems that TR is keep starting. 
@FritzHeiden and @louaybassbouss will you be able to help with further diagnostic please?

**Comment by FritzHeiden** [comment] 2021-11-17 16:27
Could you provide the test runner logs, please?
```
docker logs dpctf
```

**Comment by gitwjr** [comment] 2021-11-17 16:32
@FritzHeiden 
The entire log is filled repeatedly (at over 50X - I quit counting) with the following: 

ln: failed to create symbolic link './*': File exists

=== ERROR ================================================================
= Ownership or permissions of results directory not properly configured. =
= Set ownership to 1000:1000 and make directory writable!                =
==========================================================================

**Comment by FritzHeiden** [comment] 2021-11-17 16:40
So the test runner doesn't start, because the results directory is not writable. I don't know a solution for this right now, I have to investigate how to change permissions on windows

**Comment by gitwjr** [comment] 2021-11-17 16:47
I just went in and changed share for the entire D drive to "everyone" and went to the observation framework folder and Deploy_Files folder and also changed to "everyone". Then checked "results" folder and verified it is shared. No change when running http://localhost or http://localhost:8000/_wave/index.html. These were all shared for previous builds but perhaps the share changes when I deleted the prior builds and rebuilt. 
When rebuilding the TR, do I need to delete prior builds? I simply rename them by adding a number e.g. dpctf-deploy-master-1 so the new build adds a new dpctf-deploy-master folder with the new one. As I imported the content recently (but prior to the latest rebuild) I didn't delete the content folder. I just moved it into the new TR folder.

**Comment by gitwjr** [comment] 2021-11-17 16:50
@FritzHeiden
Entering http://localhost or the localhost IP address in a browser should not depend on Docker or the results folder shares. It is simply a loopback independent of pretty much anything else.

**Comment by jpiesing** [comment] 2021-11-18 07:47
@FritzHeiden is it possible to reverse this process? In the installer on Windows, find which user-id owns the results directory & configure docker/test runner to use that user-id?

**Comment by FritzHeiden** [comment] 2021-11-22 11:50
I pushed a fix to check for read and write permissions instead of user IDs.

@gitwjr Please pull the latest changes, rebuild the image and try again

**Comment by gitwjr** [comment] 2021-11-24 21:04
@FritzHeiden Do I need to delete the old OF or does the build replace the last build?

**Comment by gitwjr** [comment] 2021-11-26 19:13
I loaded the new OF. It has a new name <device-observation-framework-main> so I just extracted it as a new folder alongside the original OF <device-observation-framework>. I then added the new path. I ran it but neglected to add .mp4 so it didn't find the file. I saw the error "failed to locate the file" which I also see in the log file. I then reran it and it appeared to complete but I can't find any results. Nothing new in the log file and nothing in the dpctf-deploy-master/results file. All of the entries in the files show the timestamp from the initial run that failed due to leaving out the .mp4 extension. I've run it multiple times since and it appears to run to completion but none of the timestamps change and the log file only shows the failed run. 
1.  Do I need to do something between runs of the OF? I am assuming I don't have to do anything with the TR when running the OF to check the video file. I am also assuming I can run the OF on the same file multiple times rather than having to capture a new recording each time. 
2. What does the readme means when it says "The Observation Framework will analyse the recording and post the results to the Test Runner for viewing on Test Runner's results pages." I assumed it meant in the results file under the TR folder or within the results from the TR browser page but nothing shows up. Do I need to rerun the TR? If so, doesn't that simply create a new test run with a new ID in which case I would only expect to see the results of that new run which would have to be recorded and analyzed from the new recording. 
3. What does "At the end of the process the Observation Framework will rename the file recording to: <file_name>_dpctf_<session-id>.<extension>" mean? I don't see a new file name in any folder.

**Comment by gitwjr** [comment] 2021-11-28 00:04
I got it running. The Prior OF program hung up on the Windows Terminal (Powershell) with no prompt so I couldn't stop Docker using it. If I stop Docker using the Linux Terminal something changes (possibly ownership?) and the Container received a label of "other" and no longer worked with the TR. I rebuilt everything and it worked but OF program still hung up. Loaded the new OF which has a different name (-main appended) so it created a new folder. I added the path to the new folder and deleted the one to the old folder. I ran the python command but neglected to add .mp4 and the OF program hung again. This time a started a new Windows terminal to stop Docker. Then reran OF and everything worked. I received 3 fails. I am not as concerned with the fails as I am that it is now running. I attached the results json file as a txt file.
[avc_15_30_60-2021-09-09-local.txt](https://github.com/cta-wave/device-observation-framework/files/7612572/avc_15_30_60-2021-09-09-local.txt)

**Comment by jpiesing** [comment] 2021-11-28 08:07
@gitwjr Bill, do you have any ideas for how things can be improved so other people don't repeat this experience?

**Comment by gitwjr** [comment] 2021-11-28 23:32
I am going to write up what I ended up doing. It appears there is an interaction between Linux and Windows when using WSL2 that screws things up - likely related to the ownership of the files. I found that if, for example, I renamed a file using Explorer and then changed it back it would no longer be seen by Linux. Yan and Louay kept saying use Windows without WSL2 but it wasn't clear what that actually meant. It seems that, while Docker Desktop needs WSL2 and Ubuntu to be installed, all of the commands such as Build, Import, Docker Start/Stop, etc., should be run in a Windows Terminal, not under the Linux terminal pulldown in the Terminal/Powershell. Once I did that, and after they made some changes to the TR and OF, everything works fine. I am going to do a complete rebuild and document exactly the steps I take for both the TR and OF. 

BTW, a Go Pro Hero 4 does work for a 23" monitor. It is probably not good enough for a phone. Even on the monitor there is some curvature to the capture due to the wide capture angle/optics when moved close in to fill the screen although GoPro appears to do some post capture correction to the distortion when I look at a live capture versus the file after downloading. I suspect the remaining curvature may still distort the QR codes too much. If I have time I'll try my phone too just to be sure. A TV may be challenging since mine, although a 55" 4K Smart TV, is about 5 or 6 years old. They stopped updating it a few years ago. The browser may be too out of date and it may be resource limited.

**Comment by louaybassbouss** [comment] 2021-11-29 08:19
@gitwjr I am happy to hear that it is now working on your side. As @jpiesing mentioned, any feedback and improvement to the documentation is very welcome. In [dpctf-deply](https://github.com/cta-wave/dpctf-deploy), we already added [documentation](https://github.com/cta-wave/dpctf-deploy/blob/master/WINDOWS_WSL.md) for deploying the test runner under windows with WSL2.  This is based on the documentation you sent us earlier, many thanks for this. Feel free to create a pull request (or send me and @FritzHeiden by mail) if you think this page can be improved.

**Comment by yanj-github** [comment] 2021-11-29 09:27
> 

@gitwjr, Happy that you managed to get all working, you should be able to see the result on TR by clicking on the test session from the result overview page. If there are more issue please feel free to let us know. 
I terms of "Loaded the new OF which has a different name (-main appended)" the appended mian is from github that you downloaded the main branch, it appends branch name when you donwload it. 
Also OF required user to give a correct path to the mpd file, this means that you have to include correct name of the recording. Wont locate file if part of name is missing, this includes ".mp4".
To make things clear, the docker desktop provides linux system installed on windows OS. After is has been set up correctly it becomes a seperate OS to your main windows OS. Therefor the docker desktop is your other OS. Windows powersell need to be used to build docker and start stop it. Build is set up your linux OS on windows OS and start/stop is start/stop your linux OS. So all these has to be done outside the docker which is on windows main powersell or cmd. 
I dont this there is anything that you are required to do on under the Linux terminal pulldown in the Terminal/Powershell. @louaybassbouss correct me please, if I am wrong.
Also OF required to install and run outside of the docker so on the  windows main powersell or cmd. I have already updated our readme so that it says "Test Runner is deployed as a service running inside a Docker container. The Observation Framework must be installed outside of Docker or Docker Desktop and run outside of the docker from the windows command line. Make sure that the command line or PowerShell that is used for running OF is not inside the docker or docker desktop."

**Comment by gitwjr** [comment] 2021-12-01 14:58
I totally wiped my system (Ubuntu, Python, Docker, ZBar, and all WAVE components (TR, OF) and reinstalled/rebuilt the Test Suite from scratch. The only thing I didn't uninstall was WSL2. Everything works fine with just a couple of minor hiccups. I ran the OF on a new test run and there were no problems either. I had 5 fails but that could be due to the video quality and other issues. The key point is the process works. I am documenting the steps I used in detail now. I think we can close this issue.

**Comment by gitwjr** [comment] 2021-12-04 01:20
I rewrote the ReadMe for Setup on Windows using WSL2 which is currently linked from the dpctf deploy main ReadMe. It is the procedure I used after wiping and uninstalling everything and starting from scratch. It also includes both the TR and OF procedures for Windows with WSL2 so it may need to be either split in two parts or linked to from both main ReadMe pages. Please review and comment.
[Setup on Windows using WSL2.docx](https://github.com/cta-wave/device-observation-framework/files/7653087/Setup.on.Windows.using.WSL2.docx)

**Comment by jpiesing** [comment] 2021-12-06 18:40
@yanj-github @louaybassbouss @FritzHeiden

**Comment by yanj-github** [comment] 2021-12-07 09:10
Thanks @gitwjr this is useful information I will have a look, and will take OF part from it to our readme together with next release.

**Comment by louaybassbouss** [comment] 2021-12-09 10:37
Thanks @gitwjr for your efforts we will integrate  the Test Runner part of your documentation in the corresponding README files.

**Comment by gitwjr** [comment] 2021-12-14 19:51
@louaybassbouss @yanj-github The TR includes a link to the specific Windows instructions at the top of ReadMe although they haven't updated it yet with my revised instructions. I assume they are busy completing the code and addressing issues. They left the original combined Linux/Windows instructions on the main page. I reference the main page in my linked instructions as a "for more detail" reference for e.g. options, etc. But my revised instructions should be adequate for getting the basic TR and OF up and running on a Windows computer.

**Comment by yanj-github** [comment] 2021-12-16 11:51
@gitwjr Thank you very much for the document and comments. I have feteched OF part from it and added to our readme for windows set up sections where applicable. Please feel free to let us know if you have any comments.

**Comment by gitwjr** [comment] 2021-12-16 15:48
@yanj-github I read through the updated ReadMe with the revised OF Windows Installation instructions. Looks great. Thank you for all of the time and patience you and everyone else from Eurofins and Fraunhofer provided to guide me through the process.

**Closed** 2021-12-16 15:48 UTC
