### ISSUE TITLE
enable more recent version of python with the OF

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#59] opened 2023-09-25 08:34 UTC
The instructions for the OF state the following.

> Note: If your system uses python version 3.10 or greater you will have to downgrade to one of the supported versions mentioned above. Some of the python packages required by the observation framework are not supported in python version 3.10 or greater.

In the medium term, this needs to be addressed. The OF should not require python packages that are not supported in the future.

Note that Ubuntu Jammy (22.04) includes python version 3.10 so requires a downgrade.

Forked from https://github.com/cta-wave/device-observation-framework/issues/58

**Comment by yanj-github** [comment] 2023-09-25 10:43
We have fixed OpenCV version because OpenCV library is linked directly to the observation result. Specified OpenCV version at the moment is not supported to more recent version of python. Therefore, OpenCV has to be upgraded and fix to more recently version. This has to be tested and carefully done to make sure new library and python versions fully supported.

**Comment by jpiesing** [comment] 2023-09-25 11:08
> We have fixed OpenCV version because OpenCV library is linked directly to the observation result. Specified OpenCV version at the moment is not supported to more recent version of python. Therefore, OpenCV has to be upgraded and fix to more recently version. This has to be tested and carefully done to make sure new library and python versions fully supported.

Which is why I applied the "deferred" label at the same time as filing the issue :)

**Comment by yanj-github** [comment] 2024-05-14 08:46
We have tested OpenCV v4.9.0.80 with Python v3.10.12 the new library and python versions are fully supported.

We also have compared observation results with OpenCV version OpenCV v4.9.0.80 (new) and OpenCV v4.5.2.52 (current), and noticed that the results are mostly same, except, the tests that contains low resolution contents such and switching set tests QR code.

e.g: cfhd_12.5_25_50-local-fullscreen-playback-of-switching-sets_ss1-2_debug and cfhd_12.5_25_50-local-overlapping-fragments_ss1_debug tests took from Plugfest 2024 on TV2. 

- For ss1-2 newer version is better pass duration check, newer OpenCV version detects QR codes better when it dim.
_PASS: Playback duration is 60004.06ms, expected track duration is 60000.0ms. Detected duration is different by 4.06ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 0.
FAILL Playback duration 59908.42ms does not match expected duration 60000.0ms +/- tolerance of 50ms. Detected duration is different by 91.58ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 0._
- But for overlapping the older version is better on number of frames detected, only one missing frame. It might be caused by better detection of bright QR code on the older version.
_PASS: Mid frame number tolerance is 10. Following frames are missing in playout 8: 2 10 Total of missing frames is 2.
PASS: Mid frame number tolerance is 10. Following frames are missing in playout 8: 2 Total of missing frame count is 1._

The plugfest tests were taken in normal office environment not in controlled dark room. Recording taken carefully in controlled environment might not cause differences to the test results.

**Comment by yanj-github** [comment] 2024-08-28 15:29
Package numpy is installed by matplotlib that we used to plot image for helping audio debugging.
numpy 2 is out now which was not compatible with opencv.
The compatibility issue is fixed on opencv version 4.10.0.84
We will consider to use opencv version 4.10.0.84 onwards.

**Comment by yanj-github** [comment] 2024-08-30 07:40
Current latest version to date numpy 2.1.0 has a bug in reshaping function. We use this feature for audio processing using this specific version wont work with audio observation. We are looking to fix numpy package version on the set up script.

**Comment by yanj-github** [comment] 2024-09-16 15:42
Changes made to the master please feel free to close the issue when you happy.

- numpy 2.0.2
- opencv-python 4.10.0.84
- pyzbar 0.1.9

**Closed** 2024-10-22 14:19 UTC
Labels: Released, Deferred
