### ISSUE TITLE
possible error calculating expected last frame on spicing tests

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#62] opened 2023-10-06 11:47 UTC
With the Philips 20230714 recording, 4 splicing tests report an error of the form ..

> [OF] Every sample S[k,s] shall be rendered and the samples shall be rendered in increasing presentation time order. FAIL
> Xx01: Last frame found is 250, expected to end at 288. Last frame number tolerance is 0. Mid frame number tolerance is 10.
> Following frames are missing: 25 41 85 Total of missing frames is 41.

The missing frames are due to the encoding issue with AD-A1 but the last frame found issue looks to me like a bug in the OF in calculating what last frame is expected.

Looking at the recording with a video editor, frame 250 is the standard red 'end of sequence' marker so frames 251 to 288 simply don't exist.

**Comment by yanj-github** [comment] 2023-10-06 12:05
Configurations:
   "playout": [
       [1, 1, 1],  [1, 1, 2],  [1, 1, 3],  
       [2, 1, 1],  [2, 1, 2],  [2, 1, 3],
       [1, 1, 4],  [1, 1, 5],  [1, 1, 6]
     ]

"fragment_duration": "PT0H0M1.920S"
"frame_rate": "25"

Calculation:
1.92 * 6 = 11.52 * 25 = 288

I think this issue is caused by last fragment is shorter. 
And I think this issue is duplicated with what we have raised already https://github.com/cta-wave/device-observation-framework/issues/46
In progress and we are planning to include this for next release.

**Comment by yanj-github** [comment] 2023-11-01 14:23
@jpiesing We have merged audio part in it should have addressed this issue please take a look.

**Comment by gitwjr** [comment] 2023-11-21 16:56
Closed. Handled in #46 which is closed.

**Closed** 2023-11-21 16:57 UTC
Labels: duplicate
