### ISSUE TITLE
confusing error message from low-latency-short-buffer-playback

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#73] opened 2024-03-18 13:54 UTC
The OF reports the following error from low-latency-short-buffer-playback__t2.html

>             "status": "FAIL",
>             "message": "Playback duration 30005.0ms does not match expected duration 30000.0ms. Detected duration is different by 5.0ms. Minimum waiting durationn is 222.0ms, and Maximun waiting duration is 238.67ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 0.",
>             "name": "[OF] Video: The playback duration shall match the duration of the CMAF Track"
>         },

How is this a failure when the difference is 5ms but the allowed tolerance is 50ms?

Also note the two spelling errors - duration with 'nn' and maximun .

**Comment by yanj-github** [comment] 2024-04-16 13:08
We are looking at this now will committing the fix soon.

**Comment by yanj-github** [comment] 2024-04-16 14:16
@jpiesing  Changes committed please have a look.

**Comment by yanj-github** [comment] 2024-04-17 13:20
@jpiesing it seems to me a different type of failure that OF didn't capture. I am waiting for the recording to be shared. Can you let me know which device is on please so that I can look correct recording?

**Comment by jpiesing** [comment] 2024-04-17 13:37
This was TV number 7 in the London results https://standards.cta.tech/document/33900?downloadRevision=active

**Comment by jpiesing** [comment] 2024-04-17 13:56
Here's my analysis. It may be that the sequence buffering->playing->waiting->playing is not expected, particularly the 1st time in playing.

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/8d2ee91c-3b50-469f-b5ca-ed6ecad3a7fe)

**Comment by yanj-github** [comment] 2024-04-18 10:30
@jpiesing I know what this is caused by. OF calculate delay in playback based on reported playing->waiting->playing.
We just need to skip the waiting before the play start also need to skip the waiting before frame change happens (detection of frame no 2 where OF start measure duration from). I will commit the fix once we pass internal review and test.

**Comment by yanj-github** [comment] 2024-04-19 09:45
@jpiesing I suggest to change spec wording similar to https://github.com/cta-wave/device-playback-task-force/issues/122
When playback in waiting status and playing again we should take into account the ending and starting frames from waiting to play again.

**Comment by yanj-github** [comment] 2024-04-30 10:38
Spec issue raised here: https://github.com/cta-wave/device-playback-task-force/issues/128

**Comment by yanj-github** [comment] 2024-05-09 15:27
@jpiesing I just pushed a fix today due to spec update made yesterday. TV7 is pass now. 
And here are the results for 3 best devices:

- PASS: Playback duration is 30005.0ms, expected track duration is 30000.0ms. Detected duration is different by 5.0ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 0.
- FAIL: Playback duration 29715.18ms does not match expected duration 29800.0ms +/- tolerance of 50ms. Detected duration is different by 84.82ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 5. Ending missing frame number is 0.
- PASS: Playback duration is 29784.79ms, expected track duration is 29800.0ms. Detected duration is different by 15.21ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 5. Ending missing frame number is 0.

**Comment by yanj-github** [comment] 2024-05-15 08:09
@jpiesing this is can be closed and no further changes required, feel free to close this issue please.

**Closed** 2024-05-15 09:09 UTC
Labels: Released, Release V2, Blocker
